name: API - AKS - Build and deploy

on:
push:
    branches:
    - main
    paths:
    - Humongous.Healthcare/**
    - manifests/**

jobs:
build-and-deploy: 
  ACR_LOGIN_SERVER: "<replace with your ACR name>.azurecr.io"
  AKS_NAMESPACE: health-check
  CONTAINER_IMAGE: "<replace with your ACR name>.azurecr.io/humongous-healthcare-api:${{ github.sha }}"
  env: ~
  runs-on: ubuntu-latest
  steps: 
    - 
      uses: actions/checkout@master
    - 
      uses: azure/docker-login@v1
      with: 
        login-server: "${{ env.ACR_LOGIN_SERVER }}"
        password: "${{ secrets.acr_password }}"
        username: "${{ secrets.acr_username }}"
    - 
      id: build-image
      name: "Build and push image to ACR"
      run: |
          docker build "$GITHUB_WORKSPACE/Humongous.Healthcare" -f  "Humongous.Healthcare/Dockerfile" -t ${CONTAINER_IMAGE} --label dockerfile-path=Humongous.Healthcare/Dockerfile
          docker push ${CONTAINER_IMAGE}
    - 
      uses: azure/k8s-set-context@v1
      with: 
        id: login
        kubeconfig: "${{ secrets.aks_kubeConfig }}"
    - 
      name: "Create namespace"
      run: |
          namespacePresent=`kubectl get namespace | grep ${AKS_NAMESPACE} | wc -l`
          if [ $namespacePresent -eq 0 ]
          then
              echo `kubectl create namespace ${AKS_NAMESPACE}`
          fi
    - 
      name: "dockerauth - create secret"
      uses: azure/k8s-create-secret@v1
      with: 
        container-registry-password: "${{ secrets.acr_password }}"
        container-registry-url: "${{ env.ACR_LOGIN_SERVER }}"
        container-registry-username: "${{ secrets.acr_username }}"
        namespace: "${{ env.AKS_NAMESPACE }}"
        secret-name: dockerauth
    - 
      name: "cosmosdb - create secret"
      uses: Azure/k8s-create-secret@v1
      with: 
        arguments: "--from-literal=cosmosdb-account=${{ secrets.COSMOSDB_ACCOUNT }} --from-literal=cosmosdb-key=${{ secrets.COSMOSDB_KEY }}"
        namespace: "${{ env.AKS_NAMESPACE }}"
        secret-name: cosmosdb
        secret-type: generic
    - 
      uses: azure/k8s-deploy@v1.2
      with: 
        imagepullsecrets: dockerauth
        images: "${{ env.CONTAINER_IMAGE }}\n"
        manifests: |
            manifests/deployment.yml
            manifests/service.yml
        namespace: "${{ env.AKS_NAMESPACE }}"
jobs: ~
name: "API - AKS - Build and deploy"
push: 
  branches: 
    - main
  paths: 
    - Humongous.Healthcare/**
    - manifests/**
true: ~
